add health info
husarion/panther_ros pull request #102
Opened 2023-04-05 16:25 UTC by pkowalsk1

2023-04-06 20:16 UTC, Kotochleb requested changes

2023-04-06 20:16 UTC, Kotochleb commented on panther_battery/src/adc_node.py
> +                rospy.logerr(f'[{rospy.get_name()}] battery voltage critically low!')
This should throttled

2023-04-06 20:16 UTC, Kotochleb commented on panther_battery/src/adc_node.py
> +            elif battery_msg.percentage > 1.1:
I would rather look at voltage. If the value exceeds 45 volts, this should mean overvoltage. By this should be after moving average

2023-04-06 20:16 UTC, Kotochleb commented on panther_battery/src/roboteq_republisher_node.py
> +                elif battery_msg.percentage > 1.1:
Same as in other node

2023-04-18 13:47 UTC, Kotochleb requested changes
For some reason I feel like `POWER_SUPPLY_HEALTH_DEAD` and `POWER_SUPPLY_HEALTH_OVERHEAT` could yield `logfatal` instead of `logerr`, but this would look worse in code

2023-04-18 13:47 UTC, Kotochleb commented on panther_battery/src/adc_node.py
> +            -self._V_bat_hist[label][0] / self._volt_mean_length + new_val / self._volt_mean_length
A comment would be nice. I had trouble understanding what is going on. Anyway, cool approach to the problem

2023-04-18 13:47 UTC, Kotochleb commented on panther_battery/src/adc_node.py
> +                error_msg = 'Battery temperature is dangerously high!'
```suggestion
                error_msg = 'Battery is overheating!'
```
For some reason, "dangerously" sounds strange in this case. IDK

2023-04-18 19:53 UTC, pkowalsk1 commented
> For some reason I feel like `POWER_SUPPLY_HEALTH_DEAD` and `POWER_SUPPLY_HEALTH_OVERHEAT` could yield `logfatal` instead of `logerr`, but this would look worse in code

Our products never encounter fatal errors ;)

2023-04-19 11:35 UTC, Kotochleb requested changes

2023-04-19 11:35 UTC, Kotochleb commented on panther_battery/src/roboteq_republisher_node.py
> +        )
This node could have the comment as well

2023-04-21 11:21 UTC, Kotochleb approved these changes

2023-04-21 11:56 UTC, merged