APA102 cpp implementation
husarion/panther_ros pull request #108
Opened 2023-04-17 12:27 UTC by Kotochleb

bump::patch

Reduce APA102 CPU usage by rewriting it to CPP

2023-04-19 13:01 UTC, KmakD requested changes
Few more things:
- I think all namespaces should be `panther_lights` as it refers to nodes specifically created for this ROS package.
- no changes in README required at all?

2023-04-19 13:01 UTC, KmakD commented on panther_lights/CMakeLists.txt
> +  roscpp
not alphabetical order

2023-04-19 13:01 UTC, KmakD commented on panther_lights/include/panther_lights/apa102.hpp
> +#define PANTHER_LIGHTS_APA_102_HPP_
```suggestion
#ifndef PANTHER_LIGHTS_APA102_HPP_
#define PANTHER_LIGHTS_APA102_HPP_
```

2023-04-19 13:01 UTC, KmakD commented on panther_lights/include/panther_lights/lights_driver_node.hpp
> +#ifndef PANTHER_LIGHTS_DRIVER_NODE_HPP_
I would keep node name as `driver_node.cpp`. Package name should be enough to suggest this node is related to lights.

2023-04-19 13:01 UTC, KmakD commented on panther_lights/package.xml
> +  <depend>roscpp</depend>
not alphabetical order

2023-04-19 13:01 UTC, KmakD commented on panther_lights/include/panther_lights/apa102.hpp
> +  void set_global_brightness(const std::uint8_t brightness);
```suggestion

  void set_global_brightness(const std::uint8_t brightness);
```

2023-04-19 13:01 UTC, KmakD commented on panther_lights/src/lights_driver_node.cpp
> +    "lights/driver/front_panel_frame", 5, [this](const sensor_msgs::ImageConstPtr & msg) {
```suggestion
    "lights/driver/front_panel_frame", 5, [&](const sensor_msgs::ImageConstPtr & msg) {
```
I guess this would be valid too but I'm not entirely sure which one makes more sense

2023-04-19 13:01 UTC, KmakD commented on panther_lights/src/lights_driver_node.cpp
> +  ROS_INFO("[%s] Node started spinning", node_name_.c_str());
```suggestion
  ROS_INFO("[%s] Node started", node_name_.c_str());
```

2023-04-19 13:01 UTC, KmakD commented on panther_lights/src/lights_driver_node.cpp
> +  ROS_INFO("[%s] Lights are now being displayed", node_name_.c_str());
```suggestion
  ROS_INFO("[%s] LED panels initialised", node_name_.c_str());
```

2023-04-19 13:01 UTC, KmakD commented on panther_lights/src/lights_driver_node.cpp
> +    response.success = 0;
```suggestion
    response.success = false;
```

2023-04-19 13:01 UTC, KmakD commented on panther_lights/src/lights_driver_node.cpp
> +  response.success = 1;
```suggestion
  response.success = true;
```

2023-04-19 13:01 UTC, KmakD commented on panther_lights/include/panther_lights/apa102.hpp
> +  const std::uint16_t corr_blue = 62.0;
```suggestion
  const std::uint16_t corr_red_ = 255.0;
  const std::uint16_t corr_green_ = 200.0;
  const std::uint16_t corr_blue_ = 62.0;
```

2023-04-19 13:01 UTC, KmakD commented on panther_lights/include/panther_lights/lights_driver_node.hpp
> +  std::string node_name_;
```suggestion
  const std::string node_name_;
```

2023-04-19 13:01 UTC, KmakD commented on panther_lights/include/panther_lights/lights_driver_node.hpp
> +    const sensor_msgs::ImageConstPtr & msg, const apa_102::APA102 & panel,
I will just make an open question to make it similar across all nodes in all packages:
TypeConstPtr or Type::ConstPtr ?
Same goes for services Request and Response

2023-04-19 13:01 UTC, KmakD commented on panther_lights/src/apa102.cpp
> +  }
```suggestion
  static std::uint8_t mode = cs_high ? SPI_MODE_3 : SPI_MODE_3 | SPI_CS_HIGH;
```
won't it work this way?

2023-04-19 13:01 UTC, KmakD commented on panther_lights/src/apa102.cpp
> +  std::size_t buffer_size = (4 * sizeof(std::uint8_t)) + frame.size() + (4 * sizeof(std::uint8_t));
I don't know why but this look weird

2023-04-19 13:01 UTC, KmakD commented on panther_lights/src/apa102.cpp
> +    buffer[4 + pad] = 0xE0 | brightness;
`0xE0` is this correct? Seems very random

2023-04-19 13:01 UTC, KmakD commented on panther_lights/include/panther_lights/apa102.hpp
> +#endif  // PANTHER_LIGHTS_APA_102_HPP_
```suggestion
#endif  // PANTHER_LIGHTS_APA102_HPP_
```

2023-04-19 13:01 UTC, KmakD commented on panther_lights/include/panther_lights/lights_driver_node.hpp
> +#include <panther_lights/apa102.hpp>
custom project headers at the end

2023-04-19 13:01 UTC, KmakD commented on panther_lights/include/panther_lights/lights_driver_node.hpp
> +};
```suggestion
  bool set_brightness_cb(
    panther_msgs::SetLEDBrightness::Request & req,
    panther_msgs::SetLEDBrightness::Response & res);
};
```
in python nodes we use this convention

2023-04-19 13:01 UTC, KmakD commented on panther_lights/src/lights_driver_node.cpp
> +}  // namespace panther_lights_driver
```suggestion

}  // namespace panther_lights_driver
```

2023-04-19 13:01 UTC, KmakD commented on panther_lights/src/main.cpp
> +#include <image_transport/image_transport.h>
```suggestion
```
those will be included from `lights_driver_node.hpp`

2023-04-19 13:01 UTC, KmakD commented on panther_lights/include/panther_lights/lights_driver_node.hpp
> +    const std::shared_ptr<ros::NodeHandle> private_nh, std::shared_ptr<ros::NodeHandle> nh,
`private_nh` or `ph`?

2023-04-19 13:01 UTC, KmakD commented on panther_lights/src/apa102.cpp
> +#include <vector>
```suggestion
#include <cmath>
#include <fstream>
#include <stdexcept>
```
This are already included in hpp file. Maybe we should consider moving all includes to header file?

2023-04-19 13:01 UTC, KmakD commented on panther_lights/src/lights_driver_node.cpp
> +#include <panther_lights/apa102.hpp>
```suggestion
#include <filesystem>

#include <sensor_msgs/image_encodings.h>
```
already defined in hpp file

2023-04-21 12:54 UTC, Kotochleb commented on panther_lights/include/panther_lights/lights_driver_node.hpp
> +  std::string node_name_;
As we discussed, initialization lists do not use ROS api

2023-04-21 13:04 UTC, Kotochleb commented on panther_lights/src/apa102.cpp
> +    buffer[4 + pad] = 0xE0 | brightness;
This corresponds to 11100000 in binary, which is a beginning of the header in APA102C protocol

2023-04-21 13:06 UTC, Kotochleb commented on panther_lights/include/panther_lights/lights_driver_node.hpp
> +#include <panther_lights/apa102.hpp>
You already proved yourself that they should be in both places

2023-04-21 13:06 UTC, Kotochleb commented on panther_lights/src/main.cpp
> +#include <image_transport/image_transport.h>
You already proved yourself that they should be in both places

2023-04-21 13:06 UTC, Kotochleb commented on panther_lights/include/panther_lights/lights_driver_node.hpp
> +    const std::shared_ptr<ros::NodeHandle> private_nh, std::shared_ptr<ros::NodeHandle> nh,
Done

2023-04-21 13:07 UTC, Kotochleb commented on panther_lights/src/apa102.cpp
> +#include <vector>
You already proved yourself that they should be in both places

2023-04-21 13:07 UTC, Kotochleb commented on panther_lights/src/lights_driver_node.cpp
> +#include <panther_lights/apa102.hpp>
You already proved yourself that they should be in both places

2023-04-21 13:07 UTC, Kotochleb commented on panther_lights/include/panther_lights/apa102.hpp
> +#define PANTHER_LIGHTS_APA_102_HPP_
Done

2023-04-21 13:07 UTC, Kotochleb commented on panther_lights/package.xml
> +  <depend>roscpp</depend>
Done

2023-04-21 13:08 UTC, Kotochleb commented on panther_lights/include/panther_lights/lights_driver_node.hpp
> +#ifndef PANTHER_LIGHTS_DRIVER_NODE_HPP_
Done

2023-04-21 13:08 UTC, Kotochleb commented on panther_lights/CMakeLists.txt
> +  roscpp
Done

2023-04-21 13:08 UTC, Kotochleb commented on panther_lights/src/lights_driver_node.cpp
> +  ROS_INFO("[%s] Node started spinning", node_name_.c_str());
Done

2023-04-21 13:08 UTC, Kotochleb commented on panther_lights/src/lights_driver_node.cpp
> +  ROS_INFO("[%s] Lights are now being displayed", node_name_.c_str());
Done

2023-04-21 13:08 UTC, Kotochleb commented on panther_lights/include/panther_lights/lights_driver_node.hpp
> +    const sensor_msgs::ImageConstPtr & msg, const apa_102::APA102 & panel,
Done

2023-04-21 13:09 UTC, Kotochleb commented on panther_lights/src/apa102.cpp
> +  std::size_t buffer_size = (4 * sizeof(std::uint8_t)) + frame.size() + (4 * sizeof(std::uint8_t));
This gives better overview that frame is composed of 4 header bytes, data and 4 tailing bytes

2023-04-21 13:09 UTC, Kotochleb commented on panther_lights/include/panther_lights/apa102.hpp
> +#endif  // PANTHER_LIGHTS_APA_102_HPP_
Done

2023-04-24 08:07 UTC, KmakD requested changes

2023-04-24 08:07 UTC, KmakD commented on panther_lights/CMakeLists.txt
> +std_srvs
```suggestion
  image_transport
  panther_msgs
  roscpp
  rospy
  sensor_msgs
  std_msgs
  std_srvs
```

2023-04-24 08:07 UTC, KmakD commented on panther_lights/CMakeLists.txt
> +if(NOT LIBGPIOD)
```suggestion
find_library(LIBGPIOD libgpiod)

if(NOT LIBGPIOD)
```

2023-04-24 08:07 UTC, KmakD commented on panther_lights/include/panther_lights/lights_driver_node.hpp
> +#include <panther_lights/apa102.hpp>
Here I meant order, except for main header, other project headers files should be at the end.

2023-04-24 08:07 UTC, KmakD commented on panther_lights/src/apa102.cpp
> +#include <sys/ioctl.h>
```suggestion
#include <fcntl.h>
#include <linux/spi/spidev.h>
#include <sys/ioctl.h>
#include <unistd.h>
```
order

2023-04-24 08:07 UTC, KmakD commented on panther_lights/include/panther_lights/apa102.hpp
> +namespace apa_102
In my opinion namespace should refer to ROS package where given file is located. Looking at other repositories that seems to be most common practice

2023-04-24 08:07 UTC, KmakD commented on panther_lights/src/apa102.cpp
> +namespace apa_102
same as mentioned before

2023-04-24 08:07 UTC, KmakD commented on panther_lights/src/driver_node.cpp
> +DriverNode::DriverNode(
```suggestion
namespace panther_lights
{

DriverNode::DriverNode(
```

2023-04-24 08:07 UTC, KmakD commented on panther_lights/src/driver_node.cpp
> +}  // namespace panther_lights
```suggestion
}

}  // namespace panther_lights
```

2023-05-08 09:55 UTC, KmakD approved these changes
This will need another approval after hardware tests

2023-05-10 10:25 UTC, KmakD requested changes

2023-05-10 10:27 UTC, KmakD approved these changes

2023-05-10 11:08 UTC, merged