Ros1 check bat current
husarion/panther_ros pull request #118
Opened 2023-05-19 08:01 UTC by pkowalsk1

bump::patch

2023-05-24 12:10 UTC, Kotochleb requested changes

2023-05-24 12:10 UTC, Kotochleb commented on panther_battery/src/roboteq_republisher_node.py
> +                )
Since we say that the fatal voltage is 27 V we will end up with -0.53 % of charge in case of failure. I think this should be saturated in case of exceeding 1 and going below 0. Also If we reach 27 V hardware will turn of the robot

2023-05-24 12:10 UTC, Kotochleb commented on panther_battery/src/adc_node.py
> +    BAT01_CHARGING_CURR_THRESH = 0.1
```suggestion
    BAT_CHARGING_CURR_THRESH = 0.1
```
Since this parameter is used for bot batteries, I don't think there is the point specifying that `01` indicating its assignment to the battery 1

2023-05-24 12:10 UTC, Kotochleb commented on panther_battery/src/adc_node.py
> +        )
Same as in republisher node

2023-06-01 07:47 UTC, KmakD requested changes

2023-06-01 07:47 UTC, KmakD commented on panther_battery/src/adc_node.py
> +
This method looks exactly as `_count_volt_mean`. Maybe this should be one method with additional arguments?

2023-06-05 09:54 UTC, Kotochleb approved these changes

2023-06-19 10:21 UTC, pkowalsk1 commented
@KmakD I merged branch 'ros1' into `ros1-check-bat-current`

2023-06-19 10:40 UTC, KmakD approved these changes

2023-06-19 10:40 UTC, merged