Updare panther_bringup readme
husarion/panther_ros pull request #162
Opened 2023-07-29 17:43 UTC by Kotochleb

2023-07-31 10:04 UTC, KmakD requested changes

2023-07-31 10:04 UTC, KmakD commented on panther_bringup/README.md
- Missing `robot_description` launch argument.
- I'm a bit confused about adding additional lines between elements when listing them. It may have some sense for nodes but for launch arguments it seems too much. Especially that for other packages listing is done without additional spacing
- sometimes there are multiple empy lines

2023-07-31 10:04 UTC, KmakD commented on panther_bringup/README.md
> +```
Can't write it as a suggestion but I would add line before and after this and also  "```bash"

2023-07-31 10:04 UTC, KmakD commented on panther_bringup/README.md
> +```
same as above

2023-07-31 10:04 UTC, KmakD commented on panther_bringup/README.md
> +The serial number and robot version are changed according to the parameters of your real robot. In the case `PANTHER_HW_CONFIG_CORRECT` is not set to **"true"** or does not exist, it displays an erro
```suggestion
The serial number and robot version are changed according to the parameters of your real robot. If the `PANTHER_HW_CONFIG_CORRECT` is not set to **"true"** or does not exist, an error indicating incorrect hardware will be displayed after the welcome message.
```

2023-07-31 11:12 UTC, Kotochleb commented on panther_bringup/README.md
> +```
Adding it as bash will add strange coloring

2023-07-31 11:13 UTC, Kotochleb commented on panther_bringup/README.md
> +```
Here as well. This will add strange coloring. This is terminal output and bash is coloring of input commands

2023-07-31 13:17 UTC, Kotochleb commented on panther_bringup/README.md
I removed the new lines and reverted `robot_description`. They helped me while reading and correcting it, but you are right. They are a bit confusing

2023-08-01 07:52 UTC, KmakD requested changes

2023-08-01 07:52 UTC, KmakD commented on panther_bringup/README.md
> +## Bringup launch arguments
```suggestion
## Bringup launch arguments
```

2023-08-01 07:52 UTC, KmakD commented on panther_bringup/README.md
> +## Expected launch behavior
```suggestion

## Expected launch behavior
```

2023-08-01 11:35 UTC, KmakD approved these changes

2023-08-01 11:35 UTC, merged