Ros1 docs update
husarion/panther_ros pull request #167
Opened 2023-08-02 10:26 UTC by Kotochleb

bump::patch

Update all docs to match changes in software

2023-08-14 13:57 UTC, pkowalsk1 approved these changes

2023-08-17 11:47 UTC, KmakD requested changes

2023-08-17 11:47 UTC, KmakD commented on panther_driver/README.md
> +For a `/joint_states` message carrying given data:
```suggestion
For a `/joint_states` topic, message carries given data:
```
I think the meaning of this sentence was lost

2023-08-17 11:47 UTC, KmakD commented on panther_manager/README.md
> +- `charging_anim_percent` [*string*, default: **None**]: the charging  animation battery percentage value, casted to a string.
```suggestion
- `charging_anim_percent` [*string*, default: **None**]: the charging animation battery percentage value, casted to a string.
```

2023-08-17 13:14 UTC, KmakD approved these changes

2023-08-22 12:53 UTC, KmakD approved these changes

2023-08-22 12:53 UTC, merged