Ros1 add autoparsing
husarion/panther_ros pull request #186
Opened 2023-08-22 13:34 UTC by Kotochleb

bump::patch

Add metadata in README allowing for automatic parsing of documentation

2023-08-23 07:02 UTC, KmakD requested changes

2023-08-23 07:02 UTC, KmakD commented on panther_bringup/README.md
> +[//]: # (ROS_API_NODE_PUBLISHERS_START)
```suggestion
#### Parameters

[//]: # (ROS_API_NODE_PARAMETERS_START)
```

2023-08-23 07:02 UTC, KmakD commented on panther_bringup/README.md
> +[//]: # (ROS_API_NODE_PUBLISHERS_END)
```suggestion
[//]: # (ROS_API_NODE_PARAMETERS_END)
```

2023-08-23 07:02 UTC, KmakD commented on panther_lights/README.md
> +
```suggestion
```

2023-08-23 07:02 UTC, KmakD commented on panther_manager/README.md
> +
```suggestion
[//]: # (ROS_API_NODE_SERVICE_CLIENTS_START)

- `/panther/hardware/aux_power_enable` [*std_srvs/SetBool*]: enables Aux Power output.
- `/panther/hardware/e_stop_trigger` [*std_srvs/Trigger*]: triggers E-stop.
- `/panther/hardware/fan_enable` [*std_srvs/SetBool*]: enables fan.
- `/panther/lights/controller/set/animation` [*panther_msgs/SetLEDAnimation*]: allows setting animation on Bumper Lights based on animation ID.

[//]: # (ROS_API_NODE_SERVICE_CLIENTS_END)

```

2023-09-07 10:10 UTC, pkowalsk1 approved these changes

2023-09-07 10:10 UTC, merged