ROS 2 add Roboteq Battery
husarion/panther_ros pull request #206
Opened 2023-11-06 12:01 UTC by KmakD

2023-11-13 16:29 UTC, Kotochleb requested changes
Some comments start with upper case and some with lower case. I think starting all comments that start at the beginning of a sentence with an upper case letter would be a good idea

2023-11-13 16:29 UTC, Kotochleb commented on panther_battery/README.md
>  Package containing nodes monitoring and publishing internal battery state of the Husarion Panther robot.
```suggestion
Package containing nodes monitoring and publishing the internal battery state of the Husarion Panther robot.
```

2023-11-13 16:29 UTC, Kotochleb commented on panther_battery/README.md
> +- `~battery_timeout` [*float*, default: **1.0**]: specifies the timeout in seconds. If node fails to read battery data exceeding this duration, the node will publish an unknown battery state.
```suggestion
- `~battery_timeout` [*float*, default: **1.0**]: specifies the timeout in seconds. If the node fails to read battery data exceeding this duration, the node will publish an unknown battery state.
```

2023-11-13 16:29 UTC, Kotochleb commented on panther_battery/README.md
> +Publishes battery state read from ADC unit for Panther version 1.2 and above, or based on Roboteq motor controllers data for earlier versions of the robot.
```suggestion
Publishes battery state read from ADC unit for Panther version 1.2 and above, or based on Roboteq motor controllers' data for earlier versions of the robot.
```

2023-11-13 16:29 UTC, Kotochleb commented on panther_battery/README.md
> +- `~driver_state_timeout` [*float*, default: **0.2**]: specifies timeout in seconds after which driver state messages will be considered old.
Adding a namespace for ROS parameters would simplify this section of documentation and make them more intuitive.

```
- `~adc/device_0` [*string*, default: **/sys/bus/iio/devices/iio:device0**]: ADC nr 0 device IIO path.
- `~adc/device_1` [*string*, default: **/sys/bus/iio/devices/iio:device1**]: ADC nr 1 device IIO path.
- `~adc/ma_window_len/charge` [*int*, default: **10**]: window length of a moving average, used to smooth out battery charge readings.
- `~adc/ma_window_len/temp` [*int*, default: **10**]: window length of a moving average, used to smooth out battery temperature readings.
- `~roboteq/driver_state_timeout` [*float*, default: **0.2**]: specifies timeout in seconds after which driver state messages will be considered old.
```

2023-11-13 16:29 UTC, Kotochleb commented on panther_battery/src/battery_node.cpp
> +  if (panther_version < 1.2 - std::numeric_limits<float>::epsilon()) {
```suggestion
```suggestion
  const float panther_version = this->get_parameter("panther_version").as_double();
  if (panther_version < 1.2f - std::numeric_limits<float>::epsilon()) {
```
This way, the double will be automatically cast to float and the computation will not make any pointless recasting.

One question though, why do you subtract the epsilon?

2023-11-13 16:29 UTC, Kotochleb commented on panther_battery/src/battery_node.cpp
> +}
I last log will be moved to the timer callback the function can be rewritten to call `InitializeWithRoboteqBattery()` only once as a form of fallback when ADC is not available

2023-11-13 16:29 UTC, Kotochleb commented on panther_battery/src/battery_node.cpp
> +  this->declare_parameter<std::string>("adc1_device", "/home/ros/ros2_ws/src/device1");
This path is oddly specific...
Not only that, it does not match the documentation which I believe is correct

2023-11-13 16:29 UTC, Kotochleb commented on panther_battery/include/panther_battery/roboteq_battery.hpp
> +#include <cstdint>
Unnecessary import

2023-11-13 16:29 UTC, Kotochleb commented on panther_battery/src/roboteq_battery.cpp
> +void RoboteqBattery::Update(const rclcpp::Time & header_stamp, const bool)
```suggestion
void Update(const rclcpp::Time & header_stamp, const bool /* charger_connected */)
```
This shows what was the original use for the boolean variable and not cause unused error

2023-11-13 16:29 UTC, Kotochleb commented on panther_battery/src/roboteq_battery.cpp
> +  UpdateBatteryStateRaw();
I am not entirely convinced about the readability of those functions, but I will not strongly opt to change those

2023-11-13 16:29 UTC, Kotochleb commented on panther_battery/test/test_battery_node_roboteq.cpp
> +  EXPECT_FALSE(std::isnan(battery_state_->percentage));
Also at this stage the state should not be unknown I think

2023-11-13 16:29 UTC, Kotochleb commented on panther_battery/test/test_roboteq_battery.cpp
> +  const float current_1 = 0.1;
```suggestion
  const float V_bat_full = 41.4;
  const float V_bat_min = 32.0;

  const float voltage_1 = 35.0;
  const float current_1 = 0.1;
```
Why one was auto and one was float?

2023-11-14 08:32 UTC, KmakD commented on panther_battery/src/battery_node.cpp
> +  if (panther_version < 1.2 - std::numeric_limits<float>::epsilon()) {
To ensure condition is not fulfilled when panthet_version equals precisely 1.2

2023-11-14 08:47 UTC, KmakD commented on panther_battery/include/panther_battery/roboteq_battery.hpp
> +#include <cstdint>
`uint8_t` is used in line 61

2023-11-14 08:57 UTC, KmakD commented on panther_battery/test/test_battery_node_roboteq.cpp
> +  EXPECT_FALSE(std::isnan(battery_state_->percentage));
At this stage the battery state is not unknown and these tests checks exactly that.

2023-11-14 12:20 UTC, Kotochleb commented on panther_battery/src/battery_node.cpp
> +  if (panther_version < 1.2 - std::numeric_limits<float>::epsilon()) {
Adding brackets surrounding the subtraction will make the order more clear in this case

2023-11-14 12:25 UTC, Kotochleb requested changes
Comments in lines 64-66 in `adc_battery.hpp` could be better formatted. Other comments are also not beginning with upper case letters.

2023-11-14 14:23 UTC, Kotochleb approved these changes

2023-11-14 14:24 UTC, merged