Add IMU noise + basic EKF configuration
husarion/panther_ros pull request #229
Opened 2024-02-14 13:08 UTC by rafal-gorecki

Should be merged after: #225

### Modifications

- Fix EKF
- Add IMU noise
- Rearrange urdf for Gazebo sim
- Adjust covariance values

Info: Before official alpha release it's important to adjust covariance values on real platform.

2024-02-15 15:17 UTC, rafal-gorecki commented on panther_bringup/config/ekf.yaml
> +      frequency: 30.0
```suggestion
      frequency: 50.0
```

2024-02-15 15:19 UTC, rafal-gorecki commented on panther_bringup/config/ekf.yaml
> +      acceleration_limits: [2.7, 1.5, 0.0, 0.0, 0.0, 5.7]
```suggestion
      acceleration_limits: [2.7, 1.5, 0.0, 0.0, 0.0, 5.7] # Values taken from WH01_controller.yaml and WH02_controller.yaml inside panther_controller/config
```

2024-02-19 08:08 UTC, pawelirh requested changes

2024-02-19 08:08 UTC, pawelirh commented on panther_description/urdf/gazebo.urdf.xacro
Please apply formatting to this file

2024-02-19 08:08 UTC, pawelirh commented on panther_description/urdf/panther_macro.urdf.xacro
Same as above, if u could format this file after changes

2024-02-19 15:54 UTC, pawelirh approved these changes
OK 👍🏼

2024-02-20 09:11 UTC, merged