Ros2 lights tests
husarion/panther_ros pull request #234
Opened 2024-02-27 11:48 UTC by rafal-gorecki

# TODO: specify bump command and remove this description

Bump version workflow is triggered when PR is closed, it bumps version and triggers docker build that will be tagged with version number. To use it you have to specify bump type, available commands: `bump::patch`, `bump::minor` and `bump::major` (simply leave one of them in PR description and remove this description).

2024-03-25 12:33 UTC, rafal-gorecki commented
1. There is one error with the `Publish Success` test that I do not understand. For some reason, when this test is performed before other tests, the error shown in the screenshot below appears.

![image](https://github.com/husarion/panther_ros/assets/126687345/4bc00a8c-25ab-4873-a3f8-4270e30e046f)

I don't see any reason why this would happen because with each test all objects in the `DriverNodeFixture` class are destroyed.

2. I also added this line because it also caused an error similar to the one above. I don't know yet whether I should replace `true` -> `false` in this line

```cpp
  std::vector<panther_gpiod::GPIOInfo> gpio_info_storage = {panther_gpiod::GPIOInfo{
    panther_gpiod::GPIOPin::LED_SBC_SEL, gpiod::line::direction::OUTPUT, true}};
```

3. It shouldn't be, but it would be good if you ran this test once (you can use `panther-81b2-rpi:~/rafal_ws$ colcon test --packages-select panther_lights`) to check if the panther doesn't light up for a split second like a Christmas tree during the tests.

2024-03-25 14:21 UTC, KmakD requested changes

2024-03-25 14:21 UTC, KmakD commented on panther_lights/CMakeLists.txt
> +  ament_target_dependencies(${PROJECT_NAME}_test_apa102)
```suggestion
```
Not needed here

2024-03-25 14:21 UTC, KmakD commented on panther_utils/include/panther_utils/test/ros_test_utils.hpp
> + * @param node ROS node that will be spin
I think "spun" was correct

2024-03-25 14:21 UTC, KmakD commented on panther_utils/include/panther_utils/test/ros_test_utils.hpp
> +  const std::chrono::nanoseconds & timeout)
Should be milliseconds - later this method uses sleep in milliseconds so timeout in nanoseconds does not make sense.

2024-03-25 14:21 UTC, KmakD commented on panther_utils/include/panther_utils/test/ros_test_utils.hpp
> +bool WaitForFuture(const NodeT & node, FutureT & future, const std::chrono::nanoseconds & timeout)
```suggestion
bool WaitForFuture(const NodeT & node, FutureT & future, const std::chrono::milliseconds & timeout)
```
Again milliseconds should be good enough

2024-03-25 14:21 UTC, KmakD commented on panther_utils/include/panther_utils/test/ros_test_utils.hpp
> + * @param node ROS node that will be spin
```suggestion
 * @param node ROS node that will be spun
```

2024-03-25 14:21 UTC, KmakD commented on panther_utils/include/panther_utils/test/ros_test_utils.hpp
> +    if (future.wait_for(std::chrono::microseconds(10)) == std::future_status::ready) {
```suggestion
    if (future.wait_for(std::chrono::milliseconds(10)) == std::future_status::ready) {
```

2024-03-25 14:21 UTC, KmakD commented on panther_lights/include/panther_lights/test/mock_apa102.hpp
> +class MockAPA102 : public panther_lights::apa102::APA102
This looks more like a wrapper tbh. Maybe move it to test directly similar to other test files in this package. For reference: https://github.com/husarion/panther_ros/blob/7d216e0d0f84d58307553acb9f808e5860465064/panther_lights/test/test_charging_animation.cpp#L26

2024-03-25 14:21 UTC, KmakD commented on panther_lights/include/panther_lights/test/mock_driver_node.hpp
> +class MockDriverNode : public panther_lights::DriverNode::DriverNode
Same as above

2024-03-25 14:21 UTC, KmakD commented on panther_lights/include/panther_lights/test/mock_driver_node.hpp
> +  MockDriverNode(const std::string & device) : DriverNode(device) {}
```suggestion
class MockDriverNode : public panther_lights::DriverNode
{
public:
  MockDriverNode(const std::string & node_name, const rclcpp::NodeOptions & options = rclcpp::NodeOptions()) : DriverNode(node_name, options) {}
```

2024-03-25 14:21 UTC, KmakD commented on panther_lights/test/test_apa102.cpp
Have you tried to test SPISendBuffer? Reading from SPI would look sth like:
```cpp
  struct spi_ioc_transfer tr;
  memset(&tr, 0, sizeof(tr));
  tr.tx_buf = 0;
  tr.rx_buf = reinterpret_cast<std::uint64_t>(buffer.data());
  tr.len = static_cast<std::uint32_t>(buffer.size());
  tr.speed_hz = speed_;
  tr.delay_usecs = 0;
  tr.bits_per_word = kBits;

const int ret = ioctl(fd_, SPI_IOC_MESSAGE(1), &tr);
```

2024-03-25 14:21 UTC, KmakD commented on panther_lights/test/test_driver_node.cpp
> +  void TearDown() override { rclcpp::shutdown(); }
Is there a reason to use SetUp and TearDown instead of constructor and deconstructor?

2024-03-25 14:21 UTC, KmakD commented on panther_lights/test/test_driver_node.cpp
> +    msg->header.frame_id = "camera_frame";
```suggestion
    msg->header.frame_id = "image_frame";
```

2024-03-25 14:21 UTC, KmakD commented on panther_lights/test/test_apa102.cpp
> +  void TearDown() override { apa102_.reset(); }
Is there a reason to use SetUp and TearDown instead of constructor and deconstructor?

2024-03-25 14:21 UTC, KmakD commented on panther_lights/test/test_apa102.cpp
> +class APA102Test : public ::testing::Test
```suggestion
class TestAPA102 : public testing::Test
```
Just to be compatible with other tests

2024-03-25 14:21 UTC, KmakD commented on panther_lights/test/test_driver_node.cpp
> +class DriverNodeFixture : public ::testing::Test
```suggestion
class TestDriverNode : public testing::Test
```
same

2024-03-25 14:21 UTC, KmakD commented on panther_lights/test/test_driver_node.cpp
> +}
This should be separate tests

2024-03-25 14:21 UTC, KmakD commented on panther_lights/test/test_driver_node.cpp
> +  return result;
```suggestion
  testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
```

2024-03-25 14:21 UTC, KmakD commented on panther_lights/include/panther_lights/driver_node.hpp
> +  void SetPowerPin(const bool value);
Is this method used in test?

2024-03-26 10:12 UTC, rafal-gorecki commented on panther_lights/test/test_apa102.cpp
I'm not sure if the apa102 driver sends any information after spi, after receiving the data, or I would be surprised if it returns exactly the same frame.

2024-03-26 11:54 UTC, KmakD approved these changes

2024-03-26 11:54 UTC, merged