Ros2 panther manager
husarion/panther_ros pull request #246
Opened 2024-03-14 13:56 UTC by KmakD

Most of the work is done, can't be merged as it is waiting for [plugin PR](https://github.com/husarion/panther_ros/pull/232) first. Plugin PR should include merging newest ros2-devel branch.
Things to finish after plugins are added: 
- remap fan_enable, aux_enable etc. (should be /hardware/name) services controller launch
- update bringup launch 
- remove dummy_scheduler
- add shutdown_hosts.yaml 
- change ExpectThrowWithDesription to EXPECT_TRUE(IsMessageThrown) in tests

2024-03-20 15:12 UTC, pawelirh requested changes
I have some doubts regarding the architecture (coupling between different behavior trees). I'm not sure if at this exact moment, we want to pay attention to such a discussion. However, let me mention a few aspects.

- The states (received messages) are updated on the blackboard frequently.
- It's hard to scale. A new BT, or modification of an existing one demands changes in the core node and pulls after unit test modifications.
- Single responsibility for the node is not kept, since the node in this example is responsible for creating and configuring the BT and blackboard.
- Why do we push to have several independent trees, since they are in the end using the same resources and executing interchangeably (SingleThreadedExecutor)?

2024-03-20 15:12 UTC, pawelirh commented on panther_manager/config/Panther106BT.btproj
The `config` directory seems to be a bit messy. What do you think of the following idea?
- The `config` stores the node's configuration file
- A new directory (on the same level as `config` not in the config) is made to store BT-related files, let's say `behaviour_trees`

2024-03-20 15:12 UTC, pawelirh commented on panther_manager/include/panther_manager/manager_bt_node.hpp
> +using BatteryStateMsg = sensor_msgs::msg::BatteryState;
Please sort definitions alphabetically

2024-03-20 15:12 UTC, pawelirh commented on panther_manager/src/manager_bt_node.cpp
> +    {"current_anim_id", -1},
I believe all of the elements in this map should be uppercased.

2024-03-20 15:12 UTC, pawelirh commented on panther_manager/src/manager_bt_node.cpp
> +}
Can we move this function to the external header file - sth like `bt_utils`?

2024-03-20 15:12 UTC, pawelirh commented on panther_manager/src/manager_bt_node.cpp
> +  }
I would see the time interval as a parameter

2024-03-20 15:12 UTC, pawelirh commented on panther_manager/test/test_manager_bt_node.cpp
> +  void CreateBTPorjectFile(const std::string & tree_xml);
Typo

2024-03-20 15:12 UTC, pawelirh commented on panther_manager/test/test_manager_bt_node.cpp
> +}
Please move it after constructor

2024-03-20 15:12 UTC, pawelirh commented on panther_manager/test/test_manager_bt_node.cpp
> +}
This method is not compatible with the current state of `ros2-devel`, is sth that blocks us before pulling `ros2-devel` branch so further development can be made without any conflicts?

2024-03-21 08:24 UTC, KmakD commented on panther_manager/src/manager_bt_node.cpp
> +    {"current_anim_id", -1},
Only const values of the blackboard are upper case, this two can change in runtime

2024-03-21 09:00 UTC, KmakD commented on panther_manager/test/test_manager_bt_node.cpp
> +}
There was a comment explaining that this will be changed in the future, the future has come so I changed it :P

2024-03-21 09:17 UTC, KmakD commented
>     * Why do we push to have several independent trees, since they are in the end using the same resources and executing interchangeably (SingleThreadedExecutor)?

My mistake, this should be MultiThreadedExecutor. It's fixed. The idea behind two separate BTs is that safety is a crucial part of system  and should be handled independently, we don't want deadlock or some sleep behavior in lights affect safety features.

2024-03-24 15:57 UTC, pawelirh commented on panther_manager/main.cpp
What is this file for?

2024-03-24 15:57 UTC, pawelirh commented on panther_manager/src/main.cpp
> +  rclcpp::executors::MultiThreadedExecutor executor;
MultiThreadedExecutor without specified proper callback groups is in practice SingleThreadedExecutor. I assume that changes based on our latest discussion have not yet been implemented.

2024-03-24 15:57 UTC, pawelirh commented on panther_manager/src/manager_bt_node.cpp
WIll the README file be added at a later stage of the development?

2024-03-25 07:33 UTC, KmakD commented on panther_manager/main.cpp
some merging oopsie

2024-03-25 07:56 UTC, KmakD commented on panther_manager/src/manager_bt_node.cpp
No, forgot to update that. It is mostly copied from ROS 1

2024-03-25 20:27 UTC, pawelirh commented on panther_manager/src/manager_bt_node.cpp
This readme seems to be a bit overloaded, how about:
- leaving ros node-related things in the main readme file
- creating additional markdown doc for BT things

2024-03-25 20:29 UTC, pawelirh commented on panther_manager/README.md
> +[//]: # (ROS_API_NODE_PARAMETERS_END)
Timer frequency parameters are missing in the configuration file. Can we add them?

2024-03-26 08:18 UTC, pawelirh approved these changes
LGTM 👌🏼

2024-03-26 10:51 UTC, merged