ROS 2 - Fix estop threads
husarion/panther_ros pull request #249
Opened 2024-03-16 13:38 UTC by pkowalsk1

2024-03-19 09:13 UTC, KmakD requested changes

2024-03-19 09:13 UTC, KmakD commented on panther_hardware_interfaces/include/panther_hardware_interfaces/gpio_controller.hpp
> +class e_stop_reset_interrupted : public std::exception
Why not CamelCase?

2024-03-19 09:13 UTC, KmakD commented on panther_hardware_interfaces/src/panther_system_ros_interface.cpp
> +  auto search = callback_groups_.find(group_id);
```suggestion
  const auto search = callback_groups_.find(group_id);
```

2024-03-19 09:13 UTC, KmakD commented on panther_hardware_interfaces/src/panther_system.cpp
> +    rclcpp::CallbackGroupType::MutuallyExclusive);
This may throw. Is it expected for system to die if this fails?

2024-03-19 09:13 UTC, KmakD commented on panther_hardware_interfaces/src/panther_system_ros_interface.cpp
> +    }
```suggestion
    if (search->second->type() != callback_group_type) {
      throw std::runtime_error("Requested node callback group has incorrect type.");
    }
    return search->second;
```

2024-03-19 09:13 UTC, KmakD commented on panther_hardware_interfaces/src/gpio_controller.cpp
> +bool GPIOControllerPTH12X::WaitFor(std::chrono::milliseconds timeout)
this could use a brief explaining that this method is not only waiting but also checks for interruption

2024-03-25 09:26 UTC, pkowalsk1 commented on panther_hardware_interfaces/src/panther_system.cpp
> +    rclcpp::CallbackGroupType::MutuallyExclusive);
Yes, it is. Theoretically, it could cause 'safety' issues.

2024-03-25 09:41 UTC, JanBrzyk commented on panther_hardware_interfaces/include/panther_hardware_interfaces/gpio_controller.hpp
> +class e_stop_reset_interrupted : public std::exception
CamelCase approved

2024-03-25 14:33 UTC, KmakD approved these changes

2024-03-25 14:35 UTC, merged