DriverState update
husarion/panther_ros pull request #392
Opened 2024-08-19 14:23 UTC by KmakD

### Description
Due to changes in panther_msgs DriverState. This makes stack work with new msg, tests are passing. This does not aim to refactor anything with lynx in mind, just update the stack so everything still works while having universal DriverState msg. 

[Summary of the changes]

### Modifications

-

2024-08-22 10:47 UTC, pawelirh requested changes

2024-08-22 10:47 UTC, pawelirh commented on panther_battery/README.md
> +- `hardware/robot_driver_state` [*panther_msgs/DriverState*]: Current motor controllers' state and error flags. Subscribed if using Roboteq motor controllers data.
Incorrect type

2024-08-22 10:47 UTC, pawelirh commented on panther_hardware_interfaces/src/panther_system/panther_system_ros_interface.cpp
> +  RobotDriverStateMsg & robot_driver_state, const std::string & name)
```suggestion
  const RobotDriverStateMsg & robot_driver_state, const std::string & name)
```

2024-08-22 10:47 UTC, pawelirh commented on panther_hardware_interfaces/README.md
> +- `hardware/robot_driver_state` [*panther_msgs/DriverState*]: Current motor controllers' state and error flags.
Wrong type

2024-08-22 10:47 UTC, pawelirh commented on panther_manager/test/test_safety_manager_node.cpp
> +  panther_msgs::msg::DriverStateNamed motor_controller;
Why `motor_controller`?

2024-08-22 10:47 UTC, pawelirh commented on panther_manager/README.md
> +- `hardware/robot_driver_state` [*panther_msgs/DriverState*]: State of motor controllers.
type missing

2024-08-22 12:12 UTC, KmakD commented on panther_hardware_interfaces/src/panther_system/panther_system_ros_interface.cpp
> +  RobotDriverStateMsg & robot_driver_state, const std::string & name)
This method returns a non-const reference, so this param can't be read-only. It won't compile

2024-08-23 08:48 UTC, pawelirh approved these changes

2024-08-23 08:50 UTC, pawelirh commented
Once the PR on `panther_msgs` is merged, we can update its version in the `.respos` file. Afterwards the PR is to be merged 👍🏼

2024-08-23 09:42 UTC, merged