ROS 2 canopen manager and roboteq driver refactor
husarion/panther_ros pull request #396
Opened 2024-08-23 06:42 UTC by KmakD

### Description

This waits for [DriverState update PR](https://github.com/husarion/panther_ros/pull/392) to be merged.

### Modifications

-

2024-08-27 09:25 UTC, pawelirh requested changes

2024-08-27 09:25 UTC, pawelirh commented on panther_hardware_interfaces/src/panther_system/motors_controller/roboteq_driver.cpp
>  // parameter names changed, but ids stayed the same, it will be better to just use ids directly
Comment to line 32-36

- How about moving the `CANOpenObject` to `canopen_manager`?
- `CANopenObject` -> `CANOpenObject`

2024-08-27 09:25 UTC, pawelirh commented on panther_hardware_interfaces/test/unit/panther_system/motors_controller/test_roboteq_driver.cpp
> +}
Why do we test twice on these tests? I assume that the error scenario is the first assertion. If so, it seems to be enough for a test case.
Can we somehowe name the argumenets provided to the funtion, so we can have better understanding of provided values?

2024-08-27 09:25 UTC, pawelirh commented on panther_hardware_interfaces/test/unit/panther_system/motors_controller/test_roboteq_driver.cpp
> +    roboteq_driver_->GetMotorDriver(kMotor2Name)->ReadMotorDriverState();
What `fb_` stands for?

2024-08-27 09:25 UTC, pawelirh commented on panther_hardware_interfaces/test/unit/panther_system/motors_controller/test_roboteq_driver.cpp
> +  std::this_thread::sleep_for(std::chrono::milliseconds(10));
Is value 10ms correct? Don't u aimed 100ms? (I refere to 10Hz from the comment)

2024-08-27 09:25 UTC, pawelirh commented on panther_hardware_interfaces/test/unit/panther_system/motors_controller/test_roboteq_driver.cpp
> +  std::this_thread::sleep_for(std::chrono::milliseconds(50));
What is the execution time of roboteq unit tests? I understand that these sleeps are needed to operate with roboteq mock. Did we optimize them?

2024-08-27 09:25 UTC, pawelirh commented on panther_hardware_interfaces/test/unit/panther_system/motors_controller/test_roboteq_driver.cpp
> +  ASSERT_NO_THROW(roboteq_driver_->ResetScript());
Default choice should be EXPECT, expecially at the end of test case.

2024-08-27 09:25 UTC, pawelirh commented on panther_hardware_interfaces/test/unit/panther_system/motors_controller/test_roboteq_driver.cpp
> +}
```suggestion
int main(int argc, char ** argv)
{
  testing::InitGoogleTest(&argc, argv);
  
  auto result = RUN_ALL_TESTS();

  return result;
}
```

2024-08-27 09:25 UTC, pawelirh commented on panther_hardware_interfaces/test/utils/roboteqs_mock.hpp
> +   * @brief Starts CAN communication and creates a simulated Roboteq, that publish PDOs with set
If we mock one roboteq we need to rename a file, class and some descriptions.

2024-08-27 09:25 UTC, pawelirh commented on panther_hardware_interfaces/test/utils/roboteqs_mock.hpp
How about using first mock/fake/... etc. as a file and class name so we can later group them by types?

2024-08-27 10:48 UTC, KmakD commented on panther_hardware_interfaces/src/panther_system/motors_controller/roboteq_driver.cpp
>  // parameter names changed, but ids stayed the same, it will be better to just use ids directly
I'll move it. Then name of the library is actually "CANopen" so I would stick with that.

2024-08-27 10:51 UTC, KmakD commented on panther_hardware_interfaces/test/unit/panther_system/motors_controller/test_roboteq_driver.cpp
> +    roboteq_driver_->GetMotorDriver(kMotor2Name)->ReadMotorDriverState();
feedback, want it changed to sth lie driver_state_motor_1?

2024-08-27 13:21 UTC, KmakD commented on panther_hardware_interfaces/test/unit/panther_system/motors_controller/test_roboteq_driver.cpp
> +}
Copied it from different tests, no idea why it was done this way. Fixed

2024-08-27 13:22 UTC, KmakD commented on panther_hardware_interfaces/test/unit/panther_system/motors_controller/test_roboteq_driver.cpp
> +  std::this_thread::sleep_for(std::chrono::milliseconds(10));
The comment is misleading, the 10 referred to 10ms period, fixed.

2024-08-27 13:29 UTC, KmakD commented on panther_hardware_interfaces/test/unit/panther_system/motors_controller/test_roboteq_driver.cpp
> +  std::this_thread::sleep_for(std::chrono::milliseconds(50));
About 5s. This is based on roboteq_mock publishing frequencies for updating driver state. 
The most time consuming are boots, which takes about 100-150 ms for each test.

2024-09-02 12:04 UTC, pawelirh commented on panther_hardware_interfaces/test/unit/panther_system/motors_controller/test_roboteq_driver.cpp
> +    roboteq_driver_->GetMotorDriver(kMotor2Name)->ReadMotorDriverState();
Yep, I'd rename since it's not intuitive 👍🏼

2024-09-02 12:17 UTC, merged