ROS2 docking utils
husarion/panther_ros pull request #462
Opened 2024-12-11 14:31 UTC by delihus

### Description

-

### Requirements

- [ ] Code style guidelines followed
- [ ] Documentation updated

### Tests 🧪

- [ ] Robot
- [ ] Container
- [ ] Simulation

2024-12-17 18:41 UTC, delihus commented on husarion_ugv_manager/src/safety_manager_node.cpp
> +    timer_period, std::bind(&SafetyManagerNode::SafetyTreeTimerCB, this));
It could be. I have to ask @KmakD

2024-12-17 18:44 UTC, delihus commented on husarion_ugv_utils/test/test_tf2_utils.cpp
> +}
I don't know it is necessary.  Let's wait for @rafal-gorecki

2024-12-17 18:46 UTC, delihus commented on husarion_ugv_manager/src/plugins/condition/check_joy_msg.cpp
> +  }
if expected axes are empty we want to skip comparing them.

2024-12-17 18:50 UTC, delihus commented on husarion_ugv_manager/src/plugins/condition/check_joy_msg.cpp
> +  return (max_timeout <= 0.0) || time_diff < rclcpp::Duration::from_seconds(max_timeout);
We can do this. In the other nodes there are these kind of input checking but we have to add timeout and expected axes and expected buttons as fields of the class.
The getting parameters should be in the onTick then.

2024-12-17 18:50 UTC, delihus commented on husarion_ugv_manager/src/plugins/condition/check_joy_msg.cpp
> +  return (max_timeout <= 0.0) || time_diff < rclcpp::Duration::from_seconds(max_timeout);
@rafal-gorecki  what do you think?

2024-12-17 18:51 UTC, delihus commented on husarion_ugv_manager/src/plugins/condition/check_joy_msg.cpp
> +  }
if expected axes are empty we want to skip comparing them.

2024-12-17 18:57 UTC, delihus commented on husarion_ugv_utils/include/husarion_ugv_utils/tf2_utils.hpp
> +}
You are right. There can be problem near 360 degrees.

2024-12-17 19:07 UTC, delihus commented on husarion_ugv_utils/include/husarion_ugv_utils/tf2_utils.hpp
> +  }
My code works but I think my comment is also good

2024-12-17 19:08 UTC, delihus commented on husarion_ugv_manager/src/plugins/action/dock_robot_node.cpp
> +  }
Then use_dock_id is false we can just skip this parameter. It is okay

2024-12-17 19:10 UTC, delihus commented on husarion_ugv_gazebo/launch/spawn_charging_docks.launch.py
> +        return []
I also want to catch `ValueError`. It can be Exception

2024-12-17 19:12 UTC, delihus commented on husarion_ugv_manager/include/husarion_ugv_manager/plugins/condition/check_bool_msg.hpp
> +// FIXME: There is no possibility to set QoS profile. Add it in the future to subscribe e_stop.
It is followed here:
https://github.com/BehaviorTree/BehaviorTree.ROS2/pull/99
and
https://github.com/husarion/panther_ros/issues/434

2024-12-17 19:15 UTC, delihus commented on husarion_ugv_manager/include/husarion_ugv_manager/plugins/action/call_set_led_animation_service_node.hpp
> +      {BT::InputPort<unsigned>("id", "Animation ID to trigger."),
The user can add custom animations.

2024-12-17 19:16 UTC, delihus commented on husarion_ugv_manager/test/plugins/action/test_dock_robot_node.cpp
> +}
There is no  ActionResult::CANCELED

2024-12-17 19:16 UTC, delihus commented on panther_description/config/docking_components.yaml
> +    device_namespace: None
We use None when there is no device_namespace.

2024-12-17 19:18 UTC, delihus commented on husarion_ugv_manager/CMakeLists.txt
> +  list(APPEND plugin_tests ${PROJECT_NAME}_test_check_joy_msg)
they are?

2024-12-18 08:13 UTC, KmakD commented on husarion_ugv_manager/src/safety_manager_node.cpp
> +    timer_period, std::bind(&SafetyManagerNode::SafetyTreeTimerCB, this));
If there are similar parts in both files it makes sense. But if it's just calculating period and creating timer from frequency then it's overkill imo.

2024-12-18 14:08 UTC, rafal-gorecki commented on panther_manager/test/plugins/condition/test_check_bool_msg.cpp
You add this to panther_manager, but should be added to husarion_ugv_manager.

2024-12-18 14:08 UTC, rafal-gorecki commented on panther_manager/test/plugins/condition/test_check_joy_msg.cpp
You add this to panther_manager, but should be added to husarion_ugv_manager.

2024-12-18 14:17 UTC, rafal-gorecki requested changes
Waiting for your opinion

2024-12-18 14:17 UTC, rafal-gorecki commented on husarion_ugv_manager/include/husarion_ugv_manager/plugins/action/dock_robot_node.hpp
Why we keep it?

2024-12-18 14:17 UTC, rafal-gorecki commented on husarion_ugv_gazebo/launch/spawn_charging_docks.launch.py
I'm not sure, how we should spawn station. This solutions require duplicating config from docking_parameters.
Other option can be
1. Moving it into husarion_ugv_docking and run it only if use_sim=true. 
2. In other hand we can add some yaml with station position in husarion_gz_worlds.

2024-12-20 03:10 UTC, delihus commented on husarion_ugv_gazebo/launch/spawn_charging_docks.launch.py
1. Okay!
2. I think i will make a dependency between `panther-navigation` repo and `husarion_gz_worlds`

2024-12-20 03:11 UTC, delihus commented on husarion_ugv_manager/include/husarion_ugv_manager/plugins/action/dock_robot_node.hpp
Just the implementations of plugins. Should I move it to husarion_ugv_docking?

2024-12-20 14:12 UTC, delihus commented on husarion_ugv_manager/test/utils/plugin_test_utils.hpp
> +  }
I think it is very edgecase

2024-12-20 14:13 UTC, delihus commented on husarion_ugv_manager/test/plugins/action/test_dock_robot_node.cpp
> +}
I think we can skip this

2024-12-20 14:14 UTC, delihus commented on husarion_ugv_manager/src/safety_manager_node.cpp
> +    timer_period, std::bind(&SafetyManagerNode::SafetyTreeTimerCB, this));
me too. that's overkill.
Thanks @KmakD

2024-12-20 17:47 UTC, delihus commented on husarion_ugv_manager/include/husarion_ugv_manager/plugins/action/dock_robot_node.hpp
moved

2024-12-20 17:47 UTC, delihus commented on husarion_ugv_gazebo/launch/spawn_charging_docks.launch.py
moved spawn to husarion_ugv_docking

2024-12-20 19:31 UTC, rafal-gorecki approved these changes

2024-12-20 19:31 UTC, merged