Add husarion_ugv_msgs
husarion/panther_ros pull request #466
Opened 2024-12-13 11:25 UTC by rafal-gorecki

### Description

- add husarion_ugv_msgs
- repleace all occurance panther_msgs -> husarion_ugv_msgs

### Requirements

- [x] Code style guidelines followed
- [x] Documentation updated

### Tests 🧪

- [ ] Robot
- [ ] Container
- [ ] Simulation

2024-12-16 11:21 UTC, KmakD commented on ROS_API.md
> +| ✅   | ❌   | `battery/charging_status`     | Battery charging status value.<br/> [*husarion_ugv_msgs/ChargingStatus*](https://github.com/husarion/husarion_ugv_msgs)
Link should point to `panther_ros` repo and `husarion_ugv_msgs` package. Applies to all links

2024-12-16 11:21 UTC, KmakD commented on husarion_ugv_lights/test/integration/husarion_ugv_lights.test.py
>  from std_srvs.srv import SetBool
could also add line between launch imports and standard msgs

2024-12-16 11:23 UTC, KmakD requested changes
Forgot to mark this as request changes

2024-12-16 14:56 UTC, rafal-gorecki commented on husarion_ugv_lights/test/integration/husarion_ugv_lights.test.py
>  from std_srvs.srv import SetBool
pre-commit reformat it that way

2024-12-16 15:00 UTC, rafal-gorecki commented on husarion_ugv_lights/test/integration/husarion_ugv_lights.test.py
>  from std_srvs.srv import SetBool
by default isor order look like this:
```python
from __future__ import annotations  # FUTURE

import os  # STDLIB
import sys  # STDLIB

import numpy as np  # THIRDPARTY
import rospy  # THIRDPARTY

from my_project.module import MyClass  # FIRSTPARTY

from .local_module import MyLocalClass  # LOCALFOLDER
```

2024-12-17 07:45 UTC, KmakD commented on ROS_API.md
> +| ✅   | ❌   | `battery/charging_status`     | Battery charging status value.<br/> [*husarion_ugv_msgs/ChargingStatus*](husarion_ugv_msgs)
should we also change it so it points to the msg file instead of just the package?

2024-12-17 09:54 UTC, KmakD approved these changes
lgtm

2024-12-17 09:54 UTC, merged